version: '3.7'

services:
    webserver:
      image: nginx:alpine
      container_name: slim-v4-api-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./engine/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "12306:80"

    php-fpm:
      build: engine/php-fpm
      container_name: slim-v4-api-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./engine/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini